services:
  postgres:
    image: postgres:14
    container_name: tms-postgres
    restart: always
    environment:
      POSTGRES_DB: tms_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tms-network

  django:
    build: .
    container_name: tms-django
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin:admin123@postgres:5432/tms_db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - tms-network

volumes:
  postgres_data:

networks:
  tms-network:
